### ISSUE TITLE
Last Keyframe Interpolates to Rest Position

### ISSUE THREAD

**Issue by Vercidium** [chinedufn/blender-iks-to-fks#1]
Hello,

This is a great script! It solved my export problems for a lot of my animations, however for some actions in Blender it interpolates to the rest position instead of the last keyframe pose.

Here is an example showing what is happening:

https://www.youtube.com/watch?v=7OGJYOmXyl8

The first animation shown is the original armature, and the second animation shown is the one generated by this script.

Any help with this would be greatly appreciated.

**Comment by chinedufn** [comment]
Thanks a lot for the bug report! Also thanks for taking the time to upload a video!

Just to confirm - you've unchecked `Deform` for all of your control bones - yes?

---

Are you able to provide me with a minimal Blender file that illustrates this problem?

If so - I'd be very happy to take a look and see what's going wrong.

The reason that a minimal file is useful is that we can then add it to the [test suite](https://github.com/chinedufn/blender-iks-to-fks/tree/master/test).

This would just boil down to removing bones and simplifying your mesh (maybe decimate it a bunch of times) and seeing if the problem still persists. Essentially the smaller and lest complicated the file the better.

---

If you're unable to provide a minimal example - option 2 (less desirable) would be to share this file from your video with me and I can take a look and try to pair it down to a minimal reproduction of the problem.

My turn around time for this option would probably be a bit slower as I'd have to set aside time to try to pare down your file.

---

Thanks again for the report!

**Comment by Vercidium** [comment]
Thank you for the quick reply!

A few hours after I posted this issue, I figured out what was happening:

1) When I first ran the script, I only had 1 out of 2 layers selected, therefore some animation data was lost
2) I thought that this was caused by constraints not being copied across, so I commented out the part of your script that removed constraints from the FK armature
3) I ran the script again (this time unknowingly with both layers selected) and the animation luckily converted correctly
4) However for some animations (like the one in the video), they didn't convert to FK correctly
5) I reverted your script to the original, cleaned up my blender file, selected both layers and ran your export script
6) Everything converted smoothly!

Again thank you for the quick reply, I hope this scenario allows people to understand how Blender works better :)

**A quick question:**
Sometimes the FK armature has a duplicate animation, for example my animation list of:
Minigun.Walking
Minigun.Reloading
Minigun.Running

becomes:

F Minigun.Walking
F Minigun.Reloading
F Minigun.Running
Minigun.Running.001

Both Running and Running.001 have the same animation data, I'm just wondering why some animations seem to be duplicated.

Thank you again, this script is incredibly useful.

**Comment by chinedufn** [comment]
Woohoo thanks so much for explaining the solution!

> Both Running and Running.001 have the same animation data, I'm just wondering why some animations seem to be duplicated.

When we duplicate the bones the actions get duplicated as well (not sure when exactly.. I'd have to look more closely). 

I'd need to do some thinking to figure out how to address this.. At the moment I just have another script that I run that cleans up all of the duplicates..

Glad the script is useful!!! If the duplicates are causing problems for you at the moment feel free to open up another issue!
