### ISSUE TITLE
To make it work for Blender 2.8?

### ISSUE THREAD

**Issue by enzyme69** [chinedufn/blender-iks-to-fks#2]
Is there a plan to make this add-on works for Blender 2.8? Thanks!

**Comment by chinedufn** [comment]
I haven't upgraded to 2.8 yet so I didn't even know that it was broken! Thanks for the heads up!

I'd absolutely love to support Blender 2.8! 

If you can include a bit more information about what isn't working for you I can dive in and take a look.

Cheers and thanks!

**Comment by enzyme69** [comment]
@chinedufn I simply could not install the add-on with Blender 2.8.

But it was working for me with Blender 2.79. I am doing a lot of GLTF export testings, and I think your IK to FK conversion helps with some weird issues.

**Comment by chinedufn** [comment]
Gotcha - cool sounds like the APIs must've changed a little... I'll take a look as soon as I can and get a fix out

**Comment by chinedufn** [comment]
Ok just learned that 2.8 is still in beta.

Is it a problem for you to use 2.79 in the meantime? I'd prefer to wait for 2.8 to get out of beta before supporting it.

**Comment by chinedufn** [comment]
This is still on my radar - just waiting on 2.8 to be officially released!

**Comment by chinedufn** [comment]
Alright - currently working on removing 2.79 support in favor of 2.80 support

**Comment by chinedufn** [comment]
Done https://github.com/chinedufn/blender-iks-to-fks/commit/71ac64fd6dc64b9d36985163d2133e4273d5a412
